---
#- file: path=/etc/supervisor/django.conf.d/{{name}}.conf state=absent
- file: path=/etc/supervisor/conf.d/{{name}}.conf state=absent
  notify: restart supervisor
- file: path=/etc/nginx/django.conf.d/{{name}}.conf state=absent
  notify: reload nginx
